[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "statstech"
version  = "0.1.0"
description = "Biblioteca de aprendizado de máquina em NumPy"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["numpy>=1.26"]

[project.optional-dependencies]
dev = ["pytest>=8", "ruff"]

[tool.setuptools.packages.find]
where = ["src"]